---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.11

Parameters:
  RootDomain:
    Type: String
    Default: gustavomejia.tech
    Description: "Root domain for the API Gateway"

Resources:
  # 🟣 External Domain
  MyHostedDomain:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Sub "${RootDomain}"

  # 🔴 SSL Certificate
  ACMCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "*.${RootDomain}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub "*.${RootDomain}"
          HostedZoneId: !Ref MyHostedDomain

  # 🟣 Subdomain Api Gateway http api
  ExampleSubdomainApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: !Sub "${AWS::StackName}-ExampleSubdomain"  # ✅ Use Resource name
      StageName: Prod
      Domain:
        DomainName: !Sub "example.${RootDomain}"  # ✅ Ahora usa el valor correcto
        CertificateArn: !Ref ACMCertificate
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: !Ref MyHostedDomain

  # 🟠 Lambda Functions
  ExampleApi:  # ✅ Use your own name
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/ExampleFunction/  # ✅ Use your own directory
      Description: "This is an example. Use it as a reference to create your own endpoint." # ✅ Use your own description
      FunctionName: !Sub "${AWS::StackName}-ExampleApi"  # ✅ Use Resource name
      Handler: app.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ExampleAPIEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ExampleSubdomainApiGateway
            Method: GET
            Path: /example  # Use your own path

  ExampleFunction:  # Use your own name
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/ExampleFunction/  # Use your own path
      Description: "This is an example. Use it as a reference to create your own function." # ✅ Use your own description
      FunctionName: !Sub "${AWS::StackName}-ExampleFunction"  # ✅ Use Resource name
      Handler: app.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole

  HelloWorldCamicase:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/HelloWorldCamicase/
      Description: "Hello world of Camicase" # ✅ Use your own description
      FunctionName: !Sub "${AWS::StackName}-HelloWorldCamicase"  # ✅ Use Resource name
      Handler: app.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole

Outputs:
  HostedZoneNameServers:
    Description: "Please copy the name servers below to your DNS provider"
    Value: !Join [",", !GetAtt MyHostedDomain.NameServers]
  HostedZoneArn:
    Description: "Please use this Id to create records"
    Value: !GetAtt MyHostedDomain.Id
  StackInfo:
    Value: !Sub "Stack name: ${AWS::StackName}, Id: ${AWS::StackId}" 
...
