AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  # PythonDependenciesLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     LayerName: PythonDependenciesLayer
  #     Description: Layer will contain dependencies
  #     ContentUri: layers/libs-layer/
  #     CompatibleRuntimes:
  #       - python3.8
  #       - python3.9
  #       - python3.10
  #     LicenseInfo: "MIT"
  #     RetentionPolicy: Retain

  LambdaHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9  # Se usa la misma versión que en `Globals`
      Handler: app.lambda_handler
      CodeUri: .
      # Layers:
      #   - !Ref PythonDependenciesLayer
      Policies:
        - AWSLambdaBasicExecutionRole
