Resources:
  CrawlerMalpensante:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/CrawlerMalpensante/src
      Description: |
        "This script fetch the information of articles from Malpensante as rss feed"
      FunctionName: !Sub "${AWS::StackName}-CrawlerMalpensante"
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        HeadEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ExampleSubdomainApiGateway
            Method: HEAD
            Path: /rss/malpensante
        ExampleAPIEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ExampleSubdomainApiGateway
            Method: GET
            Path: /rss/malpensante
      Timeout: 300 # 300 seconds (5 minutes)
